# This file was generated by GoReleaser. DO NOT EDIT.
cask "mongoctl" do
  name "mongoctl"
  desc "A simple command-line tool for managing MongoDB connection profiles."
  homepage "https://github.com/moltinginstar/homebrew-mongoctl"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mongoctl"
  bash_completion "completions/mongoctl.bash"
  zsh_completion "completions/mongoctl.zsh"
  fish_completion "completions/mongoctl.fish"

  on_macos do
    on_intel do
      url "https://github.com/moltinginstar/mongoctl/releases/download/v#{version}/mongoctl_Darwin_x86_64.tar.gz",
        verified: "github.com/moltinginstar/homebrew-mongoctl"
      sha256 "1e15893202bc556ff76b548903bbd19ac708d5a24e0330ac07fdb57e5cea7341"
    end
    on_arm do
      url "https://github.com/moltinginstar/mongoctl/releases/download/v#{version}/mongoctl_Darwin_arm64.tar.gz",
        verified: "github.com/moltinginstar/homebrew-mongoctl"
      sha256 "70d9719c033b233897964a77f6c6326113c9d36b4a6edfe36c211f1dcd7c1612"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/moltinginstar/mongoctl/releases/download/v#{version}/mongoctl_Linux_x86_64.tar.gz",
        verified: "github.com/moltinginstar/homebrew-mongoctl"
      sha256 "7c0a7aebae1f8bb55fc332e12e7a6d044fa20c5e353cb3eff4860beca80073ef"
    end
    on_arm do
      url "https://github.com/moltinginstar/mongoctl/releases/download/v#{version}/mongoctl_Linux_arm64.tar.gz",
        verified: "github.com/moltinginstar/homebrew-mongoctl"
      sha256 "d53499dfa3142f1773f770f239655621451050691846d1b7d8fc7dd50574505f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mongoctl"]
    end
  end

  # No zap stanza required
end
