# This file was generated by GoReleaser. DO NOT EDIT.
cask "mongoctl" do
  name "mongoctl"
  desc "A simple command-line tool for managing MongoDB connection profiles."
  homepage "https://github.com/moltinginstar/homebrew-mongoctl"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mongoctl"
  bash_completion "completions/mongoctl.bash"
  zsh_completion "completions/mongoctl.zsh"
  fish_completion "completions/mongoctl.fish"

  on_macos do
    on_intel do
      url "https://github.com/moltinginstar/mongoctl/releases/download/v#{version}/mongoctl_Darwin_x86_64.tar.gz",
        verified: "github.com/moltinginstar/homebrew-mongoctl"
      sha256 "7621b3df7c22fd60501291ac3b7cb325553ad763b7bd7f3e1df2d09ea2946c46"
    end
    on_arm do
      url "https://github.com/moltinginstar/mongoctl/releases/download/v#{version}/mongoctl_Darwin_arm64.tar.gz",
        verified: "github.com/moltinginstar/homebrew-mongoctl"
      sha256 "d1210805026781ad815c8268603a0a61cc518354f6ad1143f88b3a7c5ffe9ed8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/moltinginstar/mongoctl/releases/download/v#{version}/mongoctl_Linux_x86_64.tar.gz",
        verified: "github.com/moltinginstar/homebrew-mongoctl"
      sha256 "f3f50d33768cb5ec35de114082943b235998ce7f9dbab2c7247aca3d5a1e4f4d"
    end
    on_arm do
      url "https://github.com/moltinginstar/mongoctl/releases/download/v#{version}/mongoctl_Linux_arm64.tar.gz",
        verified: "github.com/moltinginstar/homebrew-mongoctl"
      sha256 "9d3f92021cec8aabbb0da4d8a88d1aa31f599df9e123823e27deb4d99d2fe6da"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mongoctl"]
    end
  end

  # No zap stanza required
end
