# This file was generated by GoReleaser. DO NOT EDIT.
cask "mongoctl" do
  name "mongoctl"
  desc "A simple command-line tool for managing MongoDB connection profiles."
  homepage "https://github.com/moltinginstar/homebrew-mongoctl"
  version "0.4.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mongoctl"
  bash_completion "completions/mongoctl.bash"
  zsh_completion "completions/mongoctl.zsh"
  fish_completion "completions/mongoctl.fish"

  on_macos do
    on_intel do
      url "https://github.com/moltinginstar/mongoctl/releases/download/v#{version}/mongoctl_Darwin_x86_64.tar.gz",
        verified: "github.com/moltinginstar/homebrew-mongoctl"
      sha256 "5673bb0d6790b548001ffffe24faf3b307580687f4e8587b200ad0fe908eac6e"
    end
    on_arm do
      url "https://github.com/moltinginstar/mongoctl/releases/download/v#{version}/mongoctl_Darwin_arm64.tar.gz",
        verified: "github.com/moltinginstar/homebrew-mongoctl"
      sha256 "f85cb29b627146b876a0ee6a74bb406c8134030b75d0d5da272b44c0a615a195"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/moltinginstar/mongoctl/releases/download/v#{version}/mongoctl_Linux_x86_64.tar.gz",
        verified: "github.com/moltinginstar/homebrew-mongoctl"
      sha256 "d89f610501d2eca94e7313ddfd0a92ba24855953c31ec2f8eb32d3653045d7a4"
    end
    on_arm do
      url "https://github.com/moltinginstar/mongoctl/releases/download/v#{version}/mongoctl_Linux_arm64.tar.gz",
        verified: "github.com/moltinginstar/homebrew-mongoctl"
      sha256 "3a17aa9f923c2207da8429627382971fed3db69b614ae5d8cad221b483753e9e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mongoctl"]
    end
  end

  # No zap stanza required
end
